# 1.1. Arrays

# Exercise 1.1

In [2]:
import numpy as np
aa = np.array([[3,-1,4],[1,5,-9]])
bb = np.array([[2,4,-5,6],[-1,7,9,3],[3,2,-7,-2]])

cc = np.dot(aa,bb)
print("The result is : ")
print(cc)

The result is : 
[[ 19  13 -52   7]
 [-30  21 103  39]]


# Exercise 1.2

In [3]:
import numpy as np
aa = np.array([[3,-1,4],[1,5,-9]])

print(aa.ndim)
print(aa.dtype)

2
int64



# Exercise 1.3

In [44]:
import numpy as np
x = np.array([3,-4,1])
y = np.array([5,2,3])
print(x + 10)
print(y * 4 )
print(x + y)
print(x * y)


[13  6 11]
[20  8 12]
[ 8 -2  4]
[15 -8  3]


# Exercise 1.4

In [47]:
import numpy as np
A = np.array([[1, 2, 3],[4, 5, 6]])
print(A.ndim)
print(A.dtype)
print(A.shape)
print(A.size)


2
int64
(2, 3)
6


# Exercise 1.5

In [11]:
import numpy as np
A = np.array([[1, 2, 3],[4, 5, 6]])
A = A.astype('float64')
print(A.dtype)

float64


# Exercise 1.6

# What does x = np.arange(10) do?

<p> create new array of 1 to 10

In [21]:
import numpy as np
x = np.arange(10)
print(x)

print(x[3])
print(x[:4])
print(x[4:])
print(x[4:8])
print(max(x))
print(min(x))




[0 1 2 3 4 5 6 7 8 9]
3
[0 1 2 3]
[4 5 6 7 8 9]
[4 5 6 7]
9
0
[0 1 2 3 4 5 6 7 8 9]


# Exercise 1.7

In [7]:
import numpy as np
x= np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(x[1, 2])

print(x[ : , 2 : ])



7
[[2 3 4]
 [7 8 9]]


# 2. Working on Iris.csv file

In [2]:
from sklearn import datasets
iris = datasets.load_iris()
print(iris.filename)

/Users/azoz1920/opt/anaconda3/lib/python3.7/site-packages/sklearn/datasets/data/iris.csv


In [91]:
import numpy as np 
iris_data = np.genfromtxt('//Users//azoz1920//opt//anaconda3//lib//python3.7//site-packages//sklearn//datasets//data//iris.csv',
                         delimiter=",", skip_header=1)
print(iris_data)

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.2 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.9 3.6 1.4 0.1 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [5.  3.5 1

# Exercise 2:

In [6]:
import numpy as np 
iris_data = np.genfromtxt('//Users//azoz1920//opt//anaconda3//lib//python3.7//site-packages//sklearn//datasets//data//iris.csv',
                         delimiter=",", skip_header=1)

print("mean of {} is {}".format(iris.feature_names[0], iris_data[:,0].mean()))
print("std of {} is {}".format(iris.feature_names[0], iris_data[:,0].std()))
print("var of {} is {}".format(iris.feature_names[0], iris_data[:,0].var()))
print("max of {} is {}".format(iris.feature_names[0], iris_data[:,0].max()))
print("min of {} is {}".format(iris.feature_names[0], iris_data[:,0].min()))

print()

print("mean of {} is {}".format(iris.feature_names[1], iris_data[:,1].mean()))
print("std of {} is {}".format(iris.feature_names[1], iris_data[:,1].std()))
print("var of {} is {}".format(iris.feature_names[1], iris_data[:,1].var()))
print("max of {} is {}".format(iris.feature_names[1], iris_data[:,1].max()))
print("min of {} is {}".format(iris.feature_names[1], iris_data[:,1].min()))

mean of sepal length (cm) is 5.843333333333334
std of sepal length (cm) is 0.8253012917851409
var of sepal length (cm) is 0.6811222222222223
max of sepal length (cm) is 7.9
min of sepal length (cm) is 4.3

mean of sepal width (cm) is 3.0573333333333337
std of sepal width (cm) is 0.4344109677354946
var of sepal width (cm) is 0.1887128888888889
max of sepal width (cm) is 4.4
min of sepal width (cm) is 2.0
